# Basic
title: 林嘉俊的个人网站
sidetitle: linjiajun
subtitle:
welcome_message: A Web Developer
description: 芝兰生于深谷，不以无人而不芳；君子修道立德，不为困穷而改节
creator: <a href="http://www.linjiajun.com">@linjiajun</a>

url: "http://www.linjiajun.com"

permalink: /:year/:month/:title/

# Format
#highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
#    - {title: About, description: About Me, url: 'http://www.linjiajun.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#    disqus:
     duoshuo: linjiajun
    
# Social
social:
#    weibo:
    github: jiajunlin
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: qylinxia@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# 百度统计 baidu tongji
bt:
    switch: true