# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               '林嘉俊的个人博客'
tagline:             linxia blog
description:         '读读书，写写代码'
url:                 http://www.linjiajun.com
baseurl:             http://www.linjiajun.com
paginate:            5

# About/contact
author:
  name:              linjiajun
  url:               http://www.linjiajun.com
  email:             qylinxia@qq.com

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Custom vars
version:             1.0.0
