# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               '林嘉俊的个人博客'
tagline:             linjiajun blog
description:         'Standing on Shouders of Giants'
url:                 https://linnxia.github.io
baseurl:             https://linnxia.github.io
paginate:            5

# About/contact
author:
  name:              linjiajun
  url:               http://www.linjiajun.com
  email:             qylinxia@qq.com

github: https://github.com/felinxia
# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Custom vars
version:             1.0.0
