# Basic
title: LINJIAJUN'S BLOG
sidetitle: 
subtitle: 
welcome_message: Software Developer
description: The only thing I know is that I know nothing
seoDesc: 林嘉俊的个人博客、linjiajun blog、林嘉俊、linjiajun
seoKeyWord: 林嘉俊、linjiajun、linjiajun.com、 https://www.ultimate-kernel.fun
creator: <a href="https://www.ultimate-kernel.fun">@linjiajun</a>

url: "https://www.ultimate-kernel.fun"

permalink: /:year/:month/:title/

# Format
#highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About, description: About Me, url: '/about'}
    - {title: cnblogs, description: cnblogs, url: 'https://www.cnblogs.com/GeniusLyzh/'}
    # - {title: Another Button, description: A button, url: 'https://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#    disqus:
     duoshuo: linjiajun
    
# Social
social:
#    weibo:
    github: aaronlamz
    twitter: aaronlamz
#    gplus: 107108267983477358170
    mail: qylinxia@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# 百度统计 baidu tongji
baidu:
    tongji: true

# _site目录不包含的文件
exclude: ["Gemfile", "Gemfile.lock", "Rakefile"]